TERMUX_PKG_HOMEPAGE="https://github.com/termux/termux-app"
TERMUX_PKG_DESCRIPTION="AHardwareBuffer rendering bridge for Termux desktop backends"
TERMUX_PKG_LICENSE="GPL-3.0-only"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.1.0"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL="file://${TERMUX_PKG_BUILDER_DIR}/termux-render-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=adb920d359de8b8e8f923ca23c73e1671a9cf442bdf5323aa0e95277b60c2e55

TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
-DINSTALL_ASSETS=default
-DTERMUX_RENDER_FD_ONLY=OFF
-DTERMUX_RENDER_ASSETS_DIR=$TERMUX_PREFIX/share/termux-render/assets
"
